using System;
using System.Collections.Generic;
using UnityEngine.Scripting;
using BansheeGz.BGDatabase;

//=============================================================
//||                   Generated by BansheeGz Code Generator ||
//=============================================================

#pragma warning disable 414

[Preserve]
public sealed partial class MONEY : BGEntity
{
	private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
	public static BansheeGz.BGDatabase.BGMetaRow MetaDefault => _metaDefault ??= BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(5603007394887703576UL,8799717887851682957UL), () => _metaDefault = null);
	public static BansheeGz.BGDatabase.BGRepoEvents Events => BGRepo.I.Events;
	public static int CountEntities => MetaDefault.CountEntities;
	public System.String name
	{
		get => _name[Index];
		set => _name[Index] = value;
	}
	public System.Int32 ENEMY_GOLD
	{
		get => _ENEMY_GOLD[Index];
		set => _ENEMY_GOLD.SetValue(this, value);
	}
	public System.Int32 WAVE_MIN
	{
		get => _WAVE_MIN[Index];
		set => _WAVE_MIN.SetValue(this, value);
	}
	public System.Int32 WAVE_MAX
	{
		get => _WAVE_MAX[Index];
		set => _WAVE_MAX.SetValue(this, value);
	}
	public System.Int32 INITIAL_MONEY
	{
		get => _INITIAL_MONEY[Index];
		set => _INITIAL_MONEY.SetValue(this, value);
	}
	public System.Int32 SPAWN_INITIAL
	{
		get => _SPAWN_INITIAL[Index];
		set => _SPAWN_INITIAL.SetValue(this, value);
	}
	public System.Int32 SPAWN_ADDED
	{
		get => _SPAWN_ADDED[Index];
		set => _SPAWN_ADDED.SetValue(this, value);
	}
	public System.Int32 UPGRADE
	{
		get => _UPGRADE[Index];
		set => _UPGRADE.SetValue(this, value);
	}
	private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77_name;
	public static BansheeGz.BGDatabase.BGFieldEntityName _name => _ufle12jhs77_name ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(MetaDefault, new BGId(5426664343268157488UL, 3127858160888238236UL), () => _ufle12jhs77_name = null);
	private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_ENEMY_GOLD;
	public static BansheeGz.BGDatabase.BGFieldInt _ENEMY_GOLD => _ufle12jhs77_ENEMY_GOLD ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(4643541826657866573UL, 14079977612257930374UL), () => _ufle12jhs77_ENEMY_GOLD = null);
	private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_WAVE_MIN;
	public static BansheeGz.BGDatabase.BGFieldInt _WAVE_MIN => _ufle12jhs77_WAVE_MIN ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(5263201753068860970UL, 17038648128196157370UL), () => _ufle12jhs77_WAVE_MIN = null);
	private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_WAVE_MAX;
	public static BansheeGz.BGDatabase.BGFieldInt _WAVE_MAX => _ufle12jhs77_WAVE_MAX ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(5660544291343290258UL, 16346972077542152357UL), () => _ufle12jhs77_WAVE_MAX = null);
	private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_INITIAL_MONEY;
	public static BansheeGz.BGDatabase.BGFieldInt _INITIAL_MONEY => _ufle12jhs77_INITIAL_MONEY ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(5300787469910013637UL, 13082437331050159497UL), () => _ufle12jhs77_INITIAL_MONEY = null);
	private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_SPAWN_INITIAL;
	public static BansheeGz.BGDatabase.BGFieldInt _SPAWN_INITIAL => _ufle12jhs77_SPAWN_INITIAL ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(5679380120376689959UL, 5046741271556839836UL), () => _ufle12jhs77_SPAWN_INITIAL = null);
	private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_SPAWN_ADDED;
	public static BansheeGz.BGDatabase.BGFieldInt _SPAWN_ADDED => _ufle12jhs77_SPAWN_ADDED ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(5586949535779426341UL, 967944711988584577UL), () => _ufle12jhs77_SPAWN_ADDED = null);
	private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_UPGRADE;
	public static BansheeGz.BGDatabase.BGFieldInt _UPGRADE => _ufle12jhs77_UPGRADE ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(5639390524447145709UL, 12313755914397070981UL), () => _ufle12jhs77_UPGRADE = null);
	private MONEY() : base(MetaDefault) {}
	private MONEY(BGId id) : base(MetaDefault, id) {}
	private MONEY(BGMetaEntity meta) : base(meta) {}
	private MONEY(BGMetaEntity meta, BGId id) : base(meta, id) {}
	public static MONEY FindEntity(Predicate<MONEY> filter) => BGCodeGenUtils.FindEntity(MetaDefault, filter);
	public static List<MONEY> FindEntities(Predicate<MONEY> filter, List<MONEY> result=null, Comparison<MONEY> sort=null) => BGCodeGenUtils.FindEntities(MetaDefault, filter, result, sort);
	public static void ForEachEntity(Action<MONEY> action, Predicate<MONEY> filter=null, Comparison<MONEY> sort=null) => BGCodeGenUtils.ForEachEntity(MetaDefault, action, filter, sort);
	public static MONEY GetEntity(BGId entityId) => (MONEY) MetaDefault.GetEntity(entityId);
	public static MONEY GetEntity(int index) => (MONEY) MetaDefault[index];
	public static MONEY GetEntity(string entityName) => (MONEY) MetaDefault.GetEntity(entityName);
	public static MONEY NewEntity() => (MONEY) MetaDefault.NewEntity();
	public static MONEY NewEntity(BGId entityId) => (MONEY) MetaDefault.NewEntity(entityId);
	public static MONEY NewEntity(Action<MONEY> callback) => (MONEY) MetaDefault.NewEntity(new BGMetaEntity.NewEntityContext(entity => callback((MONEY)entity)));
	public static void InitializeCodeGenRuntime()
	{
		_metaDefault = BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(5603007394887703576UL,8799717887851682957UL), ReleaseCodeGenRuntime);
		_ufle12jhs77_name = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(_metaDefault, new BGId(5426664343268157488UL, 3127858160888238236UL));
		_ufle12jhs77_ENEMY_GOLD = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(_metaDefault, new BGId(4643541826657866573UL, 14079977612257930374UL));
		_ufle12jhs77_WAVE_MIN = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(_metaDefault, new BGId(5263201753068860970UL, 17038648128196157370UL));
		_ufle12jhs77_WAVE_MAX = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(_metaDefault, new BGId(5660544291343290258UL, 16346972077542152357UL));
		_ufle12jhs77_INITIAL_MONEY = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(_metaDefault, new BGId(5300787469910013637UL, 13082437331050159497UL));
		_ufle12jhs77_SPAWN_INITIAL = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(_metaDefault, new BGId(5679380120376689959UL, 5046741271556839836UL));
		_ufle12jhs77_SPAWN_ADDED = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(_metaDefault, new BGId(5586949535779426341UL, 967944711988584577UL));
		_ufle12jhs77_UPGRADE = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(_metaDefault, new BGId(5639390524447145709UL, 12313755914397070981UL));
	}
	public static void ReleaseCodeGenRuntime()
	{
		_metaDefault = null;
		_ufle12jhs77_name = null;
		_ufle12jhs77_ENEMY_GOLD = null;
		_ufle12jhs77_WAVE_MIN = null;
		_ufle12jhs77_WAVE_MAX = null;
		_ufle12jhs77_INITIAL_MONEY = null;
		_ufle12jhs77_SPAWN_INITIAL = null;
		_ufle12jhs77_SPAWN_ADDED = null;
		_ufle12jhs77_UPGRADE = null;
	}

	[Preserve]
	public sealed class Factory : BGEntity.EntityFactory
	{
		public BGEntity NewEntity(BGMetaEntity meta) => new MONEY(meta);
		public BGEntity NewEntity(BGMetaEntity meta, BGId id) => new MONEY(meta, id);
	}

	public static class __Names
	{
		public const string Meta = "MONEY";
		public const string name = "name";
		public const string ENEMY_GOLD = "ENEMY_GOLD";
		public const string WAVE_MIN = "WAVE_MIN";
		public const string WAVE_MAX = "WAVE_MAX";
		public const string INITIAL_MONEY = "INITIAL_MONEY";
		public const string SPAWN_INITIAL = "SPAWN_INITIAL";
		public const string SPAWN_ADDED = "SPAWN_ADDED";
		public const string UPGRADE = "UPGRADE";
	}
}

[Preserve]
public sealed partial class Probability : BGEntity
{
	private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
	public static BansheeGz.BGDatabase.BGMetaRow MetaDefault => _metaDefault ??= BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(5684731524531148409UL,5453736929890599856UL), () => _metaDefault = null);
	public static BansheeGz.BGDatabase.BGRepoEvents Events => BGRepo.I.Events;
	public static int CountEntities => MetaDefault.CountEntities;
	public System.String name
	{
		get => _name[Index];
		set => _name[Index] = value;
	}
	public System.Int32 LEVEL
	{
		get => _LEVEL[Index];
		set => _LEVEL.SetValue(this, value);
	}
	public System.Single TIER1
	{
		get => _TIER1[Index];
		set => _TIER1.SetValue(this, value);
	}
	public System.Single TIER2
	{
		get => _TIER2[Index];
		set => _TIER2.SetValue(this, value);
	}
	public System.Single TIER3
	{
		get => _TIER3[Index];
		set => _TIER3.SetValue(this, value);
	}
	public System.Single TIER4
	{
		get => _TIER4[Index];
		set => _TIER4.SetValue(this, value);
	}
	private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77_name;
	public static BansheeGz.BGDatabase.BGFieldEntityName _name => _ufle12jhs77_name ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(MetaDefault, new BGId(4843517377938010592UL, 13264182566218335370UL), () => _ufle12jhs77_name = null);
	private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_LEVEL;
	public static BansheeGz.BGDatabase.BGFieldInt _LEVEL => _ufle12jhs77_LEVEL ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(4634751770864652504UL, 3359543931059859391UL), () => _ufle12jhs77_LEVEL = null);
	private static BansheeGz.BGDatabase.BGFieldFloat _ufle12jhs77_TIER1;
	public static BansheeGz.BGDatabase.BGFieldFloat _TIER1 => _ufle12jhs77_TIER1 ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldFloat>(MetaDefault, new BGId(4673315291674339197UL, 11883964986103953819UL), () => _ufle12jhs77_TIER1 = null);
	private static BansheeGz.BGDatabase.BGFieldFloat _ufle12jhs77_TIER2;
	public static BansheeGz.BGDatabase.BGFieldFloat _TIER2 => _ufle12jhs77_TIER2 ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldFloat>(MetaDefault, new BGId(5689777288657360466UL, 650675087797524635UL), () => _ufle12jhs77_TIER2 = null);
	private static BansheeGz.BGDatabase.BGFieldFloat _ufle12jhs77_TIER3;
	public static BansheeGz.BGDatabase.BGFieldFloat _TIER3 => _ufle12jhs77_TIER3 ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldFloat>(MetaDefault, new BGId(5178750022247981196UL, 1908538582548578965UL), () => _ufle12jhs77_TIER3 = null);
	private static BansheeGz.BGDatabase.BGFieldFloat _ufle12jhs77_TIER4;
	public static BansheeGz.BGDatabase.BGFieldFloat _TIER4 => _ufle12jhs77_TIER4 ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldFloat>(MetaDefault, new BGId(5648533473217217616UL, 4995864119426926254UL), () => _ufle12jhs77_TIER4 = null);
	private Probability() : base(MetaDefault) {}
	private Probability(BGId id) : base(MetaDefault, id) {}
	private Probability(BGMetaEntity meta) : base(meta) {}
	private Probability(BGMetaEntity meta, BGId id) : base(meta, id) {}
	public static Probability FindEntity(Predicate<Probability> filter) => BGCodeGenUtils.FindEntity(MetaDefault, filter);
	public static List<Probability> FindEntities(Predicate<Probability> filter, List<Probability> result=null, Comparison<Probability> sort=null) => BGCodeGenUtils.FindEntities(MetaDefault, filter, result, sort);
	public static void ForEachEntity(Action<Probability> action, Predicate<Probability> filter=null, Comparison<Probability> sort=null) => BGCodeGenUtils.ForEachEntity(MetaDefault, action, filter, sort);
	public static Probability GetEntity(BGId entityId) => (Probability) MetaDefault.GetEntity(entityId);
	public static Probability GetEntity(int index) => (Probability) MetaDefault[index];
	public static Probability GetEntity(string entityName) => (Probability) MetaDefault.GetEntity(entityName);
	public static Probability NewEntity() => (Probability) MetaDefault.NewEntity();
	public static Probability NewEntity(BGId entityId) => (Probability) MetaDefault.NewEntity(entityId);
	public static Probability NewEntity(Action<Probability> callback) => (Probability) MetaDefault.NewEntity(new BGMetaEntity.NewEntityContext(entity => callback((Probability)entity)));
	public static void InitializeCodeGenRuntime()
	{
		_metaDefault = BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(5684731524531148409UL,5453736929890599856UL), ReleaseCodeGenRuntime);
		_ufle12jhs77_name = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(_metaDefault, new BGId(4843517377938010592UL, 13264182566218335370UL));
		_ufle12jhs77_LEVEL = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(_metaDefault, new BGId(4634751770864652504UL, 3359543931059859391UL));
		_ufle12jhs77_TIER1 = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldFloat>(_metaDefault, new BGId(4673315291674339197UL, 11883964986103953819UL));
		_ufle12jhs77_TIER2 = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldFloat>(_metaDefault, new BGId(5689777288657360466UL, 650675087797524635UL));
		_ufle12jhs77_TIER3 = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldFloat>(_metaDefault, new BGId(5178750022247981196UL, 1908538582548578965UL));
		_ufle12jhs77_TIER4 = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldFloat>(_metaDefault, new BGId(5648533473217217616UL, 4995864119426926254UL));
	}
	public static void ReleaseCodeGenRuntime()
	{
		_metaDefault = null;
		_ufle12jhs77_name = null;
		_ufle12jhs77_LEVEL = null;
		_ufle12jhs77_TIER1 = null;
		_ufle12jhs77_TIER2 = null;
		_ufle12jhs77_TIER3 = null;
		_ufle12jhs77_TIER4 = null;
	}

	[Preserve]
	public sealed class Factory : BGEntity.EntityFactory
	{
		public BGEntity NewEntity(BGMetaEntity meta) => new Probability(meta);
		public BGEntity NewEntity(BGMetaEntity meta, BGId id) => new Probability(meta, id);
	}

	public static class __Names
	{
		public const string Meta = "Probability";
		public const string name = "name";
		public const string LEVEL = "LEVEL";
		public const string TIER1 = "TIER1";
		public const string TIER2 = "TIER2";
		public const string TIER3 = "TIER3";
		public const string TIER4 = "TIER4";
	}
}

[Preserve]
public sealed partial class UpgradeAbility : BGEntity
{
	private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
	public static BansheeGz.BGDatabase.BGMetaRow MetaDefault => _metaDefault ??= BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(4981527269916631862UL,5572655080704517509UL), () => _metaDefault = null);
	public static BansheeGz.BGDatabase.BGRepoEvents Events => BGRepo.I.Events;
	public static int CountEntities => MetaDefault.CountEntities;
	public System.String name
	{
		get => _name[Index];
		set => _name[Index] = value;
	}
	public System.Int32 ABILITY_ID
	{
		get => _ABILITY_ID[Index];
		set => _ABILITY_ID.SetValue(this, value);
	}
	public System.String ABILITY_NAME
	{
		get => _ABILITY_NAME[Index];
		set => _ABILITY_NAME[Index] = value;
	}
	public System.String DESCRIPTION
	{
		get => _DESCRIPTION[Index];
		set => _DESCRIPTION[Index] = value;
	}
	public System.Int32 MAX_RANK
	{
		get => _MAX_RANK[Index];
		set => _MAX_RANK.SetValue(this, value);
	}
	private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77_name;
	public static BansheeGz.BGDatabase.BGFieldEntityName _name => _ufle12jhs77_name ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(MetaDefault, new BGId(5604517367844950245UL, 5799269725645492653UL), () => _ufle12jhs77_name = null);
	private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_ABILITY_ID;
	public static BansheeGz.BGDatabase.BGFieldInt _ABILITY_ID => _ufle12jhs77_ABILITY_ID ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(5132743428556148199UL, 9143158430985605779UL), () => _ufle12jhs77_ABILITY_ID = null);
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_ABILITY_NAME;
	public static BansheeGz.BGDatabase.BGFieldString _ABILITY_NAME => _ufle12jhs77_ABILITY_NAME ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(5301067485773456565UL, 9313438382847457678UL), () => _ufle12jhs77_ABILITY_NAME = null);
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_DESCRIPTION;
	public static BansheeGz.BGDatabase.BGFieldString _DESCRIPTION => _ufle12jhs77_DESCRIPTION ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(5707410446859957749UL, 10946962929014996642UL), () => _ufle12jhs77_DESCRIPTION = null);
	private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_MAX_RANK;
	public static BansheeGz.BGDatabase.BGFieldInt _MAX_RANK => _ufle12jhs77_MAX_RANK ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(5233448958865690097UL, 1006679501638521252UL), () => _ufle12jhs77_MAX_RANK = null);
	private UpgradeAbility() : base(MetaDefault) {}
	private UpgradeAbility(BGId id) : base(MetaDefault, id) {}
	private UpgradeAbility(BGMetaEntity meta) : base(meta) {}
	private UpgradeAbility(BGMetaEntity meta, BGId id) : base(meta, id) {}
	public static UpgradeAbility FindEntity(Predicate<UpgradeAbility> filter) => BGCodeGenUtils.FindEntity(MetaDefault, filter);
	public static List<UpgradeAbility> FindEntities(Predicate<UpgradeAbility> filter, List<UpgradeAbility> result=null, Comparison<UpgradeAbility> sort=null) => BGCodeGenUtils.FindEntities(MetaDefault, filter, result, sort);
	public static void ForEachEntity(Action<UpgradeAbility> action, Predicate<UpgradeAbility> filter=null, Comparison<UpgradeAbility> sort=null) => BGCodeGenUtils.ForEachEntity(MetaDefault, action, filter, sort);
	public static UpgradeAbility GetEntity(BGId entityId) => (UpgradeAbility) MetaDefault.GetEntity(entityId);
	public static UpgradeAbility GetEntity(int index) => (UpgradeAbility) MetaDefault[index];
	public static UpgradeAbility GetEntity(string entityName) => (UpgradeAbility) MetaDefault.GetEntity(entityName);
	public static UpgradeAbility NewEntity() => (UpgradeAbility) MetaDefault.NewEntity();
	public static UpgradeAbility NewEntity(BGId entityId) => (UpgradeAbility) MetaDefault.NewEntity(entityId);
	public static UpgradeAbility NewEntity(Action<UpgradeAbility> callback) => (UpgradeAbility) MetaDefault.NewEntity(new BGMetaEntity.NewEntityContext(entity => callback((UpgradeAbility)entity)));
	public static void InitializeCodeGenRuntime()
	{
		_metaDefault = BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(4981527269916631862UL,5572655080704517509UL), ReleaseCodeGenRuntime);
		_ufle12jhs77_name = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(_metaDefault, new BGId(5604517367844950245UL, 5799269725645492653UL));
		_ufle12jhs77_ABILITY_ID = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(_metaDefault, new BGId(5132743428556148199UL, 9143158430985605779UL));
		_ufle12jhs77_ABILITY_NAME = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(_metaDefault, new BGId(5301067485773456565UL, 9313438382847457678UL));
		_ufle12jhs77_DESCRIPTION = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(_metaDefault, new BGId(5707410446859957749UL, 10946962929014996642UL));
		_ufle12jhs77_MAX_RANK = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(_metaDefault, new BGId(5233448958865690097UL, 1006679501638521252UL));
	}
	public static void ReleaseCodeGenRuntime()
	{
		_metaDefault = null;
		_ufle12jhs77_name = null;
		_ufle12jhs77_ABILITY_ID = null;
		_ufle12jhs77_ABILITY_NAME = null;
		_ufle12jhs77_DESCRIPTION = null;
		_ufle12jhs77_MAX_RANK = null;
	}

	[Preserve]
	public sealed class Factory : BGEntity.EntityFactory
	{
		public BGEntity NewEntity(BGMetaEntity meta) => new UpgradeAbility(meta);
		public BGEntity NewEntity(BGMetaEntity meta, BGId id) => new UpgradeAbility(meta, id);
	}

	public static class __Names
	{
		public const string Meta = "UpgradeAbility";
		public const string name = "name";
		public const string ABILITY_ID = "ABILITY_ID";
		public const string ABILITY_NAME = "ABILITY_NAME";
		public const string DESCRIPTION = "DESCRIPTION";
		public const string MAX_RANK = "MAX_RANK";
	}
}

[Preserve]
public static class BGCodeGenRuntimeInitializer
{
	[Preserve]
	public static void InitializeCodeGenRuntime()
	{
		MONEY.InitializeCodeGenRuntime();
		Probability.InitializeCodeGenRuntime();
		UpgradeAbility.InitializeCodeGenRuntime();
	}
	[Preserve]
	public static void ReleaseCodeGenRuntime()
	{
		MONEY.ReleaseCodeGenRuntime();
		Probability.ReleaseCodeGenRuntime();
		UpgradeAbility.ReleaseCodeGenRuntime();
	}
}
#pragma warning restore 414
