using System;
using System.Collections.Generic;
using UnityEngine.Scripting;
using BansheeGz.BGDatabase;

//=============================================================
//||                   Generated by BansheeGz Code Generator ||
//=============================================================

#pragma warning disable 414

[Preserve]
public sealed partial class MONEY : BGEntity
{
	private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
	public static BansheeGz.BGDatabase.BGMetaRow MetaDefault => _metaDefault ??= BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(5603007394887703576UL,8799717887851682957UL), () => _metaDefault = null);
	public static BansheeGz.BGDatabase.BGRepoEvents Events => BGRepo.I.Events;
	public static int CountEntities => MetaDefault.CountEntities;
	public System.String name
	{
		get => _name[Index];
		set => _name[Index] = value;
	}
	public System.Int32 ENEMY_GOLD
	{
		get => _ENEMY_GOLD[Index];
		set => _ENEMY_GOLD.SetValue(this, value);
	}
	public System.Int32 WAVE_MIN
	{
		get => _WAVE_MIN[Index];
		set => _WAVE_MIN.SetValue(this, value);
	}
	public System.Int32 WAVE_MAX
	{
		get => _WAVE_MAX[Index];
		set => _WAVE_MAX.SetValue(this, value);
	}
	public System.Int32 INITIAL_MONEY
	{
		get => _INITIAL_MONEY[Index];
		set => _INITIAL_MONEY.SetValue(this, value);
	}
	public System.Int32 SPAWN_INITIAL
	{
		get => _SPAWN_INITIAL[Index];
		set => _SPAWN_INITIAL.SetValue(this, value);
	}
	public System.Int32 SPAWN_ADDED
	{
		get => _SPAWN_ADDED[Index];
		set => _SPAWN_ADDED.SetValue(this, value);
	}
	public System.Int32 UPGRADE
	{
		get => _UPGRADE[Index];
		set => _UPGRADE.SetValue(this, value);
	}
	private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77_name;
	public static BansheeGz.BGDatabase.BGFieldEntityName _name => _ufle12jhs77_name ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(MetaDefault, new BGId(5426664343268157488UL, 3127858160888238236UL), () => _ufle12jhs77_name = null);
	private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_ENEMY_GOLD;
	public static BansheeGz.BGDatabase.BGFieldInt _ENEMY_GOLD => _ufle12jhs77_ENEMY_GOLD ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(4643541826657866573UL, 14079977612257930374UL), () => _ufle12jhs77_ENEMY_GOLD = null);
	private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_WAVE_MIN;
	public static BansheeGz.BGDatabase.BGFieldInt _WAVE_MIN => _ufle12jhs77_WAVE_MIN ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(5263201753068860970UL, 17038648128196157370UL), () => _ufle12jhs77_WAVE_MIN = null);
	private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_WAVE_MAX;
	public static BansheeGz.BGDatabase.BGFieldInt _WAVE_MAX => _ufle12jhs77_WAVE_MAX ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(5660544291343290258UL, 16346972077542152357UL), () => _ufle12jhs77_WAVE_MAX = null);
	private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_INITIAL_MONEY;
	public static BansheeGz.BGDatabase.BGFieldInt _INITIAL_MONEY => _ufle12jhs77_INITIAL_MONEY ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(5300787469910013637UL, 13082437331050159497UL), () => _ufle12jhs77_INITIAL_MONEY = null);
	private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_SPAWN_INITIAL;
	public static BansheeGz.BGDatabase.BGFieldInt _SPAWN_INITIAL => _ufle12jhs77_SPAWN_INITIAL ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(5679380120376689959UL, 5046741271556839836UL), () => _ufle12jhs77_SPAWN_INITIAL = null);
	private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_SPAWN_ADDED;
	public static BansheeGz.BGDatabase.BGFieldInt _SPAWN_ADDED => _ufle12jhs77_SPAWN_ADDED ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(5586949535779426341UL, 967944711988584577UL), () => _ufle12jhs77_SPAWN_ADDED = null);
	private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_UPGRADE;
	public static BansheeGz.BGDatabase.BGFieldInt _UPGRADE => _ufle12jhs77_UPGRADE ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(5639390524447145709UL, 12313755914397070981UL), () => _ufle12jhs77_UPGRADE = null);
	private MONEY() : base(MetaDefault) {}
	private MONEY(BGId id) : base(MetaDefault, id) {}
	private MONEY(BGMetaEntity meta) : base(meta) {}
	private MONEY(BGMetaEntity meta, BGId id) : base(meta, id) {}
	public static MONEY FindEntity(Predicate<MONEY> filter) => BGCodeGenUtils.FindEntity(MetaDefault, filter);
	public static List<MONEY> FindEntities(Predicate<MONEY> filter, List<MONEY> result=null, Comparison<MONEY> sort=null) => BGCodeGenUtils.FindEntities(MetaDefault, filter, result, sort);
	public static void ForEachEntity(Action<MONEY> action, Predicate<MONEY> filter=null, Comparison<MONEY> sort=null) => BGCodeGenUtils.ForEachEntity(MetaDefault, action, filter, sort);
	public static MONEY GetEntity(BGId entityId) => (MONEY) MetaDefault.GetEntity(entityId);
	public static MONEY GetEntity(int index) => (MONEY) MetaDefault[index];
	public static MONEY GetEntity(string entityName) => (MONEY) MetaDefault.GetEntity(entityName);
	public static MONEY NewEntity() => (MONEY) MetaDefault.NewEntity();
	public static MONEY NewEntity(BGId entityId) => (MONEY) MetaDefault.NewEntity(entityId);
	public static MONEY NewEntity(Action<MONEY> callback) => (MONEY) MetaDefault.NewEntity(new BGMetaEntity.NewEntityContext(entity => callback((MONEY)entity)));
	public static void InitializeCodeGenRuntime()
	{
		_metaDefault = BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(5603007394887703576UL,8799717887851682957UL), ReleaseCodeGenRuntime);
		_ufle12jhs77_name = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(_metaDefault, new BGId(5426664343268157488UL, 3127858160888238236UL));
		_ufle12jhs77_ENEMY_GOLD = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(_metaDefault, new BGId(4643541826657866573UL, 14079977612257930374UL));
		_ufle12jhs77_WAVE_MIN = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(_metaDefault, new BGId(5263201753068860970UL, 17038648128196157370UL));
		_ufle12jhs77_WAVE_MAX = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(_metaDefault, new BGId(5660544291343290258UL, 16346972077542152357UL));
		_ufle12jhs77_INITIAL_MONEY = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(_metaDefault, new BGId(5300787469910013637UL, 13082437331050159497UL));
		_ufle12jhs77_SPAWN_INITIAL = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(_metaDefault, new BGId(5679380120376689959UL, 5046741271556839836UL));
		_ufle12jhs77_SPAWN_ADDED = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(_metaDefault, new BGId(5586949535779426341UL, 967944711988584577UL));
		_ufle12jhs77_UPGRADE = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(_metaDefault, new BGId(5639390524447145709UL, 12313755914397070981UL));
	}
	public static void ReleaseCodeGenRuntime()
	{
		_metaDefault = null;
		_ufle12jhs77_name = null;
		_ufle12jhs77_ENEMY_GOLD = null;
		_ufle12jhs77_WAVE_MIN = null;
		_ufle12jhs77_WAVE_MAX = null;
		_ufle12jhs77_INITIAL_MONEY = null;
		_ufle12jhs77_SPAWN_INITIAL = null;
		_ufle12jhs77_SPAWN_ADDED = null;
		_ufle12jhs77_UPGRADE = null;
	}

	[Preserve]
	public sealed class Factory : BGEntity.EntityFactory
	{
		public BGEntity NewEntity(BGMetaEntity meta) => new MONEY(meta);
		public BGEntity NewEntity(BGMetaEntity meta, BGId id) => new MONEY(meta, id);
	}

	public static class __Names
	{
		public const string Meta = "MONEY";
		public const string name = "name";
		public const string ENEMY_GOLD = "ENEMY_GOLD";
		public const string WAVE_MIN = "WAVE_MIN";
		public const string WAVE_MAX = "WAVE_MAX";
		public const string INITIAL_MONEY = "INITIAL_MONEY";
		public const string SPAWN_INITIAL = "SPAWN_INITIAL";
		public const string SPAWN_ADDED = "SPAWN_ADDED";
		public const string UPGRADE = "UPGRADE";
	}
}

[Preserve]
public static class BGCodeGenRuntimeInitializer
{
	[Preserve]
	public static void InitializeCodeGenRuntime() => MONEY.InitializeCodeGenRuntime();
	[Preserve]
	public static void ReleaseCodeGenRuntime() => MONEY.ReleaseCodeGenRuntime();
}
#pragma warning restore 414
